// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYGiPVQSpst0ZrVvErjFTKYpnkJFkhZII',
    appId: '1:181675201017:web:6464bd4be1ffede55d2d28',
    messagingSenderId: '181675201017',
    projectId: 'se-kaleidoscope-collaborative',
    authDomain: 'se-kaleidoscope-collaborative.firebaseapp.com',
    storageBucket: 'se-kaleidoscope-collaborative.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8P-O2mbaU4AsM05oQ7XRUwtz0MbrTGCM',
    appId: '1:181675201017:android:30eb779fb42a4dc25d2d28',
    messagingSenderId: '181675201017',
    projectId: 'se-kaleidoscope-collaborative',
    storageBucket: 'se-kaleidoscope-collaborative.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIElL1Tpnfnl0-frbTU82niyJw-MVfFOw',
    appId: '1:181675201017:ios:f64dbe73fada17795d2d28',
    messagingSenderId: '181675201017',
    projectId: 'se-kaleidoscope-collaborative',
    storageBucket: 'se-kaleidoscope-collaborative.appspot.com',
    iosBundleId: 'com.example.kaleidoscopeCollaborative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIElL1Tpnfnl0-frbTU82niyJw-MVfFOw',
    appId: '1:181675201017:ios:8a9b36a07fbec85c5d2d28',
    messagingSenderId: '181675201017',
    projectId: 'se-kaleidoscope-collaborative',
    storageBucket: 'se-kaleidoscope-collaborative.appspot.com',
    iosBundleId: 'com.example.kaleidoscopeCollaborative.RunnerTests',
  );
}
